services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
